language: java
install: true
sudo: required
services:
- docker
jdk: oraclejdk8

env:
  - BUILD_DIR=jpasskit
  - BUILD_DIR=jpasskit.server

before_deploy:
- mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
- export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep
  -v '\[')

cache:
  directories:
  - "$HOME/.cache"


before_install: cd $BUILD_DIR


# deploy:
#   provider: releases
#   api_key:
#     secure: Sm0tfwrDMY6G62itcRcx8CRKv34QIJtf0lElywlLqgpyARAB9nAhf9/Pv9Iw9pAPY28CC6Q88ZHTcG/kno+wLUu7ROvcz/lHhefVVU8OmWJxRBhsY90kD3ge/8KApRGqM+IKVb8f7X+xrbCMy0dMUjV5Ii/cbUE5co5EWQv1ISNn02qLf2C+BHegZ5Kz1/YPpy4mFlKtSpmdc7eNG+xXB330A6QQo6ns63c69vtZZ1OZIqM1TQ6U9/7xRx45Qr3xQcrlk9hDj8qNCEUAmsVpYdjrnNVyyAkObbxemXuvCensEhDsuHgcsnqUzJ4WqQCQpdU3EPAGD176vu0oNSlhK26eAI065BmMWfncsjvT4GF8UtfMne/+xigFZUl0h2NKa5xrsBSvZSAoqgHZkNP2m9F7iVnwUfyuETKXgAEoE2NvR5Pm7n6o/Hj13KwEIo8rKhPi+4OKdlRvN4U+LBP12fWAoOXzP5BKXnk5OYBe3NL9Apf0V1Kjcb2PcmCGZNY8vyO+tF1QwRbL0tEJccjns5X8WWfRt56LEMLTz1uZiXshllqgcmthsqtOsZ0jRS+fXtPHCFGlEBLoxaLOCWLyQ7q5FMgaQUf+LjNe/Hp26Da9G1exbc3/ebtDLAjvmVJYPOY3AkJxE2AETEKiU7tD/AAfN+gA/uVJNCzKI0jAr3U=
#   file: jpasskit/target/jpasskit-$project_version.jar
#   on:
#     repo: drallgood/jpasskit
#   skip_cleanup: true
#   name: $project_version